begin
        SeGuarda := ItsExecuteFlQuery('select 1 from LAHER_C_N.dbo.ERP_EMPRESAS where ID = '+ ItsFlasSqlStr(Delta,'ID'));
        if SeGuarda = 1 then
            ItsRollBack('La empresa que desea agregar en esta base ya existe en CN');
        if SeGuarda <> 1 then
        ItsExecuteCommand('insert into LAHER_C_N.dbo.ERP_EMPRESAS ' +
                          '(FK_ERP_RUBROS, '+
                          ' FK_ERP_ORI_EMP, '+
                          ' FK_ERP_PER_EMP, '+
                          ' FK_ERP_TIP_EMP, '+
                          ' FK_ERP_ASESORES, '+
                          ' FK_ERP_ASESORES2, '+
                          ' FK_ERP_ASESORES3, '+
                          ' CLIENTE, '+
                          ' TE, '+
                          ' FAX, '+
                          ' CP, '+
                          ' EMAIL, '+
                          ' WEBSITE, '+
                          ' OBSERVACIONES, '+
                          ' DESCRIPCION, '+
                          ' PROVEEDOR, '+
                          ' FK_ERP_SUCURSALES, '+
                          ' N_ING_BRUTOS, '+
                          ' FK_ERP_TIP_DOC, '+
                          ' FK_ERP_TRANSPORTES, '+
                          ' FK_ERP_ZONAS, '+
                          ' DESCUENTO, '+
                          ' LIM_CREDITO, '+
                          ' CALLE, '+
                          ' PISO, '+
                          ' DEPTO, '+
                          ' FK_ERP_LOCALIDADES, '+
                          ' FK_ERP_PARTIDOS, '+
                          ' FK_ERP_PROVINCIAS, '+
                          ' FK_ERP_PAISES, '+
                          ' FK_ERP_LIS_PRECIO, '+
                          ' FK_ERP_CAT_IVA, '+
                          ' FK_ERP_CON_VEN, '+
                          ' NUM_DOC, '+
                          ' NUMERO, '+
                          ' FK_ERP_ALICUOTAS, '+
                          ' FK_ERP_CON_COM, '+
                          ' NOM_FANTASIA, '+
                          ' BON_ART, '+
                          ' FK_ERP_COBRADORES, '+
                          ' ATRASO, '+
                          ' ORIGEN, '+
                          ' ERP_CAN_VENTAS, '+
                          ' FK_ERP_GRU_EMP, '+
                          ' NUM_ONCCA, '+
                          ' OTROS_CREDITOS, '+
                          ' HORARIO, '+
                          ' FK_ERP_LIS_COM, '+
                          ' NUM_DOC_EXT, '+
                          ' POR_IVA_EXE, '+
                          ' POR_IB_EXE, '+
                          ' ORDEN, '+
                          ' CBU, '+
                          ' FK_ERP_TECNICOS, '+
                          ' FK_ERP_PRI_SER, '+
                          ' FEC_ULT_ACT, '+
                          ' EST_EXP_SUC, '+
                          ' ID, '+
                          ' FK_ERP_EXPRESOS, '+
                          ' ACTIVIDAD, '+
                          ' CATEGORIA, '+
                          ' FK_ERP_MON_COM, '+
                          ' SIT_IB_CABA, '+
                          ' SIT_IB_BSAS, '+
                          ' SIT_IB_SFE, '+
                          ' CAT_REG_OPE_AGR, '+
                          ' SIT_REG_OPE_AGR, '+
                          ' FEC_PUB_INC_AGR, '+
                          ' FEC_SUS_AGR, '+
                          ' TIP_VEN_AGR, '+
                          ' TIP_COM_AGR, '+
                          ' _CAN_MIN, '+
                          ' _CAN_MAX, '+
                          ' _IMP_MIN, '+
                          ' _IMP_MAX, '+
                          ' _COE, '+
                          ' _COE_COM, '+
                          ' _COM_EMP, '+
                          ' _DIR_EXP_DBF, '+
                          ' _METROS, '+
                          ' _ORDEN, '+
                          ' SIT_IB_MISIONES '+
                          ') values '+
                          '( '+ ItsFLAsSQLStr(delta, 'FK_ERP_RUBROS')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_ORI_EMP')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_PER_EMP')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_TIP_EMP')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_ASESORES')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_ASESORES2')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_ASESORES3')+',  '+
                                ItsFLAsSQLStr(delta, 'CLIENTE')+',  '+
                                ItsFLAsSQLStr(delta, 'TE')+',  '+
                                ItsFLAsSQLStr(delta, 'FAX')+',  '+
                                ItsFLAsSQLStr(delta, 'CP')+',  '+
                                ItsFLAsSQLStr(delta, 'EMAIL')+',  '+
                                ItsFLAsSQLStr(delta, 'WEBSITE')+',  '+
                                ItsFLAsSQLStr(delta, 'OBSERVACIONES')+',  '+
                                ItsFLAsSQLStr(delta, 'DESCRIPCION')+',  '+
                                ItsFLAsSQLStr(delta, 'PROVEEDOR')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_SUCURSALES')+',  '+
                                ItsFLAsSQLStr(delta, 'N_ING_BRUTOS')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_TIP_DOC')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_TRANSPORTES')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_ZONAS')+',  '+
                                ItsFLAsSQLStr(delta, 'DESCUENTO')+',  '+
                                ItsFLAsSQLStr(delta, 'LIM_CREDITO')+',  '+
                                ItsFLAsSQLStr(delta, 'CALLE')+',  '+
                                ItsFLAsSQLStr(delta, 'PISO')+',  '+
                                ItsFLAsSQLStr(delta, 'DEPTO')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_LOCALIDADES')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_PARTIDOS')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_PROVINCIAS')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_PAISES')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_LIS_PRECIO')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_CAT_IVA')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_CON_VEN')+',  '+
                                ItsFLAsSQLStr(delta, 'NUM_DOC')+',  '+
                                ItsFLAsSQLStr(delta, 'NUMERO')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_ALICUOTAS')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_CON_COM')+',  '+
                                ItsFLAsSQLStr(delta, 'NOM_FANTASIA')+',  '+
                                ItsFLAsSQLStr(delta, 'BON_ART')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_COBRADORES')+',  '+
                                ItsFLAsSQLStr(delta, 'ATRASO')+',  '+
                                ItsFLAsSQLStr(delta, 'ORIGEN')+',  '+
                                ItsFLAsSQLStr(delta, 'ERP_CAN_VENTAS')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_GRU_EMP')+',  '+
                                ItsFLAsSQLStr(delta, 'NUM_ONCCA')+',  '+
                                ItsFLAsSQLStr(delta, 'OTROS_CREDITOS')+',  '+
                                ItsFLAsSQLStr(delta, 'HORARIO')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_LIS_COM')+',  '+
                                ItsFLAsSQLStr(delta, 'NUM_DOC_EXT')+',  '+
                                ItsFLAsSQLStr(delta, 'POR_IVA_EXE')+',  '+
                                ItsFLAsSQLStr(delta, 'POR_IB_EXE')+',  '+
                                ItsFLAsSQLStr(delta, 'ORDEN')+',  '+
                                ItsFLAsSQLStr(delta, 'CBU')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_TECNICOS')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_PRI_SER')+',  '+
                                ItsFLAsSQLStr(delta, 'FEC_ULT_ACT')+',  '+
                                ItsFLAsSQLStr(delta, 'EST_EXP_SUC')+',  '+
                                ItsFLAsSQLStr(delta, 'ID')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_EXPRESOS')+',  '+
                                ItsFLAsSQLStr(delta, 'ACTIVIDAD')+',  '+
                                ItsFLAsSQLStr(delta, 'CATEGORIA')+',  '+
                                ItsFLAsSQLStr(delta, 'FK_ERP_MON_COM')+',  '+
                                ItsFLAsSQLStr(delta, 'SIT_IB_CABA')+',  '+
                                ItsFLAsSQLStr(delta, 'SIT_IB_BSAS')+',  '+
                                ItsFLAsSQLStr(delta, 'SIT_IB_SFE')+',  '+
                                ItsFLAsSQLStr(delta, 'CAT_REG_OPE_AGR')+',  '+
                                ItsFLAsSQLStr(delta, 'SIT_REG_OPE_AGR')+',  '+
                                ItsFLAsSQLStr(delta, 'FEC_PUB_INC_AGR')+',  '+
                                ItsFLAsSQLStr(delta, 'FEC_SUS_AGR')+',  '+
                                ItsFLAsSQLStr(delta, 'TIP_VEN_AGR')+',  '+
                                ItsFLAsSQLStr(delta, 'TIP_COM_AGR')+',  '+
                                ItsFLAsSQLStr(delta, '_CAN_MIN')+',  '+
                                ItsFLAsSQLStr(delta, '_CAN_MAX')+',  '+
                                ItsFLAsSQLStr(delta, '_IMP_MIN')+',  '+
                                ItsFLAsSQLStr(delta, '_IMP_MAX')+',  '+
                                ItsFLAsSQLStr(delta, '_COE')+',  '+
                                ItsFLAsSQLStr(delta, '_COE_COM')+',  '+
                                ItsFLAsSQLStr(delta, '_COM_EMP')+',  '+
                                ItsFLAsSQLStr(delta, '_DIR_EXP_DBF')+',  '+
                                ItsFLAsSQLStr(delta, '_METROS')+',  '+
                                ItsFLAsSQLStr(delta, '_ORDEN')+',  '+
                                ItsFLAsSQLStr(delta, 'SIT_IB_MISIONES')+ ' )');

                                ItsInfo('También grabó la empresa en la CN.');

end;